# Generated by Django 4.2.13 on 2026-05-28 16:51

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_document_file_document_status_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=768),
        ),
    ]
