# Generated by Django 4.2.13 on 2026-05-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationticket',
            name='agent_reply',
            field=models.TextField(blank=True, help_text="Agent's resolution response", null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='idx_conversation_created'),
        ),
        migrations.AddIndex(
            model_name='escalationticket',
            index=models.Index(fields=['priority'], name='idx_ticket_priority'),
        ),
        migrations.AddIndex(
            model_name='escalationticket',
            index=models.Index(fields=['status'], name='idx_ticket_status'),
        ),
    ]
