# Generated by Django 4.2.13 on 2026-06-01 10:08

from django.db import migrations
import pgvector.django.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_escalationticket_agent_reply_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='docchunk_embed_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
